config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :search, only: %i[show new edit] do
    post '/', to: 'searches#search'
  end

  resources :trains do
    resources :tickets, only: %i[new create]
  end

  resources :tickets, only: %i[index show destroy]

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :tickets, only: %i[index show destroy ]
    resources :railway_stations do
      member do
        put :update_position
        put :update_datetime
      end
    end
    resources :routes
    resource :welcomes
  end

  root 'searches#show'

end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  validates :title, presence: true
  has_many :trains
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  scope :ordered, lambda {
    select('railway_stations.*, railway_stations_routes.station_index')
      .joins(:railway_stations_routes)
      .order('railway_stations_routes.station_index').uniq
  }

  def update_position(route, index)
    station_route = station_route(route)
    station_route&.update(station_index: index)
  end

  def index(route)
    station_route(route)&.station_index
  end

  def arrival_time(route)
    station_route(route)&.arrival_time
  end

  def departure_time(route)
    station_route(route)&.departure_time
  end

  def update_datetime(route, arrival_time, departure_time)
    station_route = station_route(route)
    station_route&.update(arrival_time: arrival_time, departure_time: departure_time)
  end

  protected

  def station_route(route)
    @station_route ||= railway_stations_routes.find_by(route: route)
  end
end

app/controllers/admin/railway_stations_controller.rb
class Admin::RailwayStationsController < Admin::BaseController
  before_action :set_railway_station, only: %i[ show edit update destroy update_position update_datetime]

  # GET /railway_stations or /railway_stations.json
  def index
    @railway_stations = RailwayStation.all
  end

  # GET /railway_stations/1 or /railway_stations/1.json
  def show; end

  # GET /railway_stations/new
  def new
    @railway_station = RailwayStation.new
  end

  # GET /railway_stations/1/edit
  def edit; end

  # POST /railway_stations or /railway_stations.json
  def create
    @railway_station = RailwayStation.new(railway_station_params)

    respond_to do |format|
      if @railway_station.save
        format.html { redirect_to admin_railway_station_path(@railway_station), notice: 'Railway station was successfully created.' }
        format.json { render :show, status: :created, location: @railway_station }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /railway_stations/1 or /railway_stations/1.json
  def update
    respond_to do |format|
      if @railway_station.update(railway_station_params)
        format.html { redirect_to admin_railway_stations_path, notice: 'Railway station was successfully updated.' }
        format.json { render :show, status: :ok, location: @railway_station }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_position
    route = Route.find(params[:route_id])
    return redirect_to admin_route_path(route) unless @railway_station.update_position(route, params[:station_index])

    redirect_to admin_route_path(route), notice: 'Station index was successfully updated.'
  end

  def update_datetime
    route = Route.find(params[:route_id])
    return redirect_to admin_route_path(route) unless @railway_station.update_datetime(route, params[:arrival_time],
                                                                                       params[:departure_time])

    redirect_to admin_route_path(route), notice: 'Station datetime was successfully updated'
  end

  # DELETE /railway_stations/1 or /railway_stations/1.json
  def destroy
    @railway_station.destroy
    respond_to do |format|
      format.html { redirect_to admin_railway_stations_path, notice: 'Railway station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_railway_station
    @railway_station = RailwayStation.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def railway_station_params
    params.require(:railway_station).permit(:title)
  end
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/views/admin/railway_stations/_form.html.erb
<%= form_for [:admin, railway_station], html: { style: "display: #{hidden ? 'none' : 'block'}" } do |form| %>
  <%= render 'common/errors', resource: railway_station %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/railway_stations/edit.html.erb
<h1>Editing Railway Station</h1>

<%= render 'form', railway_station: @railway_station, hidden: false %>

<%= link_to 'Show', admin_railway_station_path(@railway_station) %> |
<%= link_to 'Back', admin_railway_stations_path %>

app/views/admin/railway_stations/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Railway Stations</h1>
<table class="table">
  <thead>
  <tr>
    <th>Title</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @railway_stations.each do |railway_station| %>
    <tr>
      <td>
        <div id="railway_station_title_<%= railway_station.id %>">
          <%= railway_station.title %>
        </div>
        <%= render 'form', railway_station: railway_station, hidden: true %>
      </td>
      <td><%= link_to 'Show', [:admin, railway_station] %></td>
      <td><%= link_to 'Edit', '', class: 'edit_station', data: { station_id: railway_station.id } %></td>
      <td><%= link_to 'Destroy', admin_railway_station_path(railway_station), method: :delete %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Railway Station', new_admin_railway_station_path %>

app/views/admin/railway_stations/new.html.erb
<h1>New Railway Station</h1>

<%= render 'form', railway_station: @railway_station, hidden: false %>

<%= link_to 'Back', admin_railway_stations_path %>

app/views/admin/railway_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @railway_station.title %>
</p>

<%= link_to 'Edit', edit_admin_railway_station_path(@railway_station) %> |
<%= link_to 'Back', admin_railway_stations_path %>