config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :search, only: %i[show new edit] do
    post '/', to: 'searches#search'
  end

  resources :trains do
    resources :tickets, only: %i[new create]
  end

  resources :tickets, only: %i[index show destroy]

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :tickets, only: %i[index show destroy ]
    resources :railway_stations do
      member do
        put :update_position
        put :update_datetime
      end
    end
    resources :routes
    resource :welcomes
  end

  root 'searches#show'

end

app/models/route.rb
class Route < ActiveRecord::Base
  validates :name, presence: true
  has_many :trains
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes, dependent: :destroy
  validate :stations_count
  before_validation :set_name
  before_validation :set_default_index

  scope :ordered_railway_stations, -> { joins(:railway_stations_routes).order('railway_stations_routes.station_index') }
  scope :with_station, ->(station) { joins(:railway_stations).where('railway_stations.id = ?', station.id) }

  def self.find_routes(start_station, end_station)
    with_station(start_station) & with_station(end_station)
  end

  def first_station
    railway_stations.first
  end

  def last_station
    railway_stations.last
  end

  private

  def set_default_index
    railway_stations_routes.each.with_index do |station, index|
      station.station_index ||= index
    end
  end

  def set_name
    self.name = "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end

  def stations_count
    errors.add(:base, 'Route must have minimum 2 station') if railway_stations_routes.count > 2
  end
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: %i[show edit update destroy]

  def index
    @routes = Route.all
  end

  def new
    @route = Route.new
  end

  def show; end

  def edit; end

  def create
    @route = Route.new(route_params)
    return render :new unless @route.save

    redirect_to admin_route_path(@route)
  end

  def update
    return render :edit unless @route.update(route_params)

    redirect_to admin_route_path(@route)
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path
  end

  private

  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end

  def set_route
    @route = Route.find(params[:id])
  end
end

app/views/admin/routes/_form.html.erb
<%= form_for [:admin, route], html: { style: "display: #{hidden ? 'none' : 'display'}" } do |form| %>
  <%= render 'common/errors', resource: route %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :railway_station_ids, 'Station' %>
    <%= form.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/routes/edit.html.erb
<h1>Edit route</h1>

<%= render 'form', route: @route, hidden: false %>

<%= link_to 'Back', admin_routes_path %>

app/views/admin/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routes</h1>

<table class="table">
  <thead>
  <tr>
    <th>Title</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @routes.each do |route| %>
    <tr>
      <td>
        <div id="route_title_<%= route.id %>">
          <%= route.name %>
        </div>
        <%= render 'form', route: route, hidden: true %>
      </td>
      <td><%= link_to 'Show', [:admin, route] %></td>
      <td><%= link_to 'Edit', '', class: 'edit_route', data: { route_id: route.id } %></td>
      <td><%= link_to 'Destroy', [:admin, route], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New route', new_admin_route_path %>

app/views/admin/routes/new.html.erb
<h1>New route</h1>

<%= render 'form', route: @route, hidden: false %>

<%= link_to 'Back', admin_routes_path %>

app/views/admin/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @route.name %>
</p>
<div>
  <table>
    <thead>
    <tr>
      <td>Station</td>
      <td>Position</td>
      <td>Arrived time</td>
      <td>Departure time</td>
    </tr>
    </thead>
    <tbody>
    <% @route.railway_stations.ordered.each do |station| %>
      <tr>
        <td><%= station.title %></td>
        <td>
          <%= form_tag update_position_admin_railway_station_path(station.id), method: :put do %>
            <%= hidden_field_tag :route_id, @route.id %>
            <%= number_field_tag :station_index, station.index(@route.id) %>
            <%= submit_tag 'Save' %>
          <% end %>
        </td>
        <td>
          <%= form_tag update_datetime_admin_railway_station_path(station.id), method: :put do %>
            <%= hidden_field_tag :route_id, @route.id %>
            <%= time_field_tag :arrival_time, station.arrival_time(@route.id) %>
          <td><%= time_field_tag :departure_time, station.departure_time(@route.id) %></td>
          <td><%= submit_tag 'Save' %></td>
        <% end %>
        </td>

      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<div>
  <% if @route.trains %>
    <strong>Trains: </strong>
    <ul>
      <% @route.trains.each do |train| %>
        <li><%= train.number %></li>
      <% end %>
    </ul>
  <% else %>
    <strong>there are no trains on the route</strong>
  <% end %>
</div>
<%= link_to 'Edit', edit_admin_route_path(@route) %> |
<%= link_to 'Back', admin_routes_path %>