config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :search, only: %i[show new edit] do
    post '/', to: 'searches#search'
  end

  resources :trains do
    resources :tickets, only: %i[new create]
  end

  resources :tickets, only: %i[index show destroy]

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :tickets, only: %i[index show destroy ]
    resources :railway_stations do
      member do
        put :update_position
        put :update_datetime
      end
    end
    resources :routes
    resource :welcomes
  end

  root 'searches#show'

end

app/models/train.rb
class Train < ApplicationRecord
  validates :number, presence: true
  has_many :tickets
  has_many :carriages, ->(train) { order("number #{train.order_carriage ? 'ASC' : 'DESC'}") }
  belongs_to :route
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id

  def number_of_seats_by_type(carriage_type, seats_type)
    carriages.where(type: carriage_type).sum(seats_type)
  end
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: %i[ show edit update destroy ]

  # GET /trains or /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1 or /trains/1.json
  def show; end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit; end

  # POST /trains or /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to admin_train_path(@train), notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1 or /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to admin_trains_path, notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1 or /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to admin_trains_path, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_train
    @train = Train.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def train_params
    params.require(:train).permit(:number, :route_id, :current_station_id, :order_carriage)
  end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.erb
<%= form_for [:admin, train], html: { style: "display: #{hidden ? 'none' : 'display'}" } do |form| %>
  <%= render 'common/errors', resource: train %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :route, 'Current route' %>
    <%= form.collection_select :route_id, Route.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :current_station, 'Current station' %>
    <%= form.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>
  <div class="field">
    <%= form.label 'From Head' %>
    <%= form.select :order_carriage, [true, false] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train, hidden: false %>

<%= link_to 'Show', admin_train_path(@train) %> |
<%= link_to 'Back', admin_trains_path %>

app/views/admin/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>

<table class="table">
  <thead>
  <tr>
    <th>Number</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @trains.each do |train| %>
    <tr>
      <td>
        <div id="train_number_<%= train.id %>">
          <%= train.number %>
        </div>
        <%= render 'form', train: train, hidden: true %>
      </td>
      <td><%= link_to 'Show', [:admin, train] %></td>
      <td><%= link_to 'Edit', '', class: 'edit_train', data: { train_id: train.id } %></td>
      <td><%= link_to 'Destroy', [:admin, train], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_admin_train_path %>

app/views/admin/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train, hidden: false %>

<%= link_to 'Back', admin_trains_path %>

app/views/admin/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>
<p>
  <% if @train.route %>
    <strong>current route: <%= @train.route.name %></strong>
  <% else %>
    <strong>Route not assigned
    </strong>
  <% end %>
</p>
<p>
  <% if @train.current_station %>
    <strong>current station: <%= @train.current_station.title %></strong>
  <% else %>
    <strong>Station not assigned
    </strong>
  <% end %>
</p>

<% if @train.carriages %>
  <table>
    <thead>
    <tr>
      <th>Carriages</th>
      <% if @train.order_carriage %>
        <p><strong>From head</strong></p>
      <% else %>
        <p><strong>From tail</strong></p>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% @train.carriages.each do |carriage| %>
      <tr>
        <td><%= link_to "#{carriage.number}", admin_carriage_path(carriage) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br>
<% else %>
  nothing
<% end %>
<%= link_to 'Add new carriage', new_admin_train_carriage_path(@train) %>
<%= link_to 'Edit', edit_admin_train_path(@train) %> |
<%= link_to 'Back', admin_trains_path %>