config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :search, only: %i[show new edit] do
    post '/', to: 'searches#search'
  end

  resources :trains do
    resources :tickets, only: %i[new create]
  end

  resources :tickets, only: %i[index show destroy]

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :tickets, only: %i[index show destroy ]
    resources :railway_stations do
      member do
        put :update_position
        put :update_datetime
      end
    end
    resources :routes
    resource :welcomes
  end

  root 'searches#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carriage.rb
class Carriage < ActiveRecord::Base
  TYPES = %w[CoupeCarriage CvCarriage EcoCarriage SeatCarriage].freeze
  validates :type, :number, presence: true
  validates :number, uniqueness: { scope: :train_id }
  belongs_to :train

  before_validation :set_number

  def set_number
    self.number ||= last_number + 1
  end

  protected

  def last_number
    train.carriages.pluck(:number).max || 0
  end

end

app/models/coupe_carriage.rb
class CoupeCarriage < Carriage
  validates :top_seats, :bottom_seats, presence: true
end

app/models/cv_carriage.rb
class CvCarriage < Carriage
  validates :bottom_seats, presence: true
end

app/models/eco_carriage.rb
class EcoCarriage < Carriage
  validates :top_seats, :bottom_seats, :side_bottom_seats, :side_top_seats, presence: true
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  validates :title, presence: true
  has_many :trains
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  scope :ordered, lambda {
    select('railway_stations.*, railway_stations_routes.station_index')
      .joins(:railway_stations_routes)
      .order('railway_stations_routes.station_index').uniq
  }

  def update_position(route, index)
    station_route = station_route(route)
    station_route&.update(station_index: index)
  end

  def index(route)
    station_route(route)&.station_index
  end

  def arrival_time(route)
    station_route(route)&.arrival_time
  end

  def departure_time(route)
    station_route(route)&.departure_time
  end

  def update_datetime(route, arrival_time, departure_time)
    station_route = station_route(route)
    station_route&.update(arrival_time: arrival_time, departure_time: departure_time)
  end

  protected

  def station_route(route)
    @station_route ||= railway_stations_routes.find_by(route: route)
  end
end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ActiveRecord::Base
  belongs_to :railway_station
  belongs_to :route

  validates :railway_station_id, uniqueness: { scope: :route_id }
  validates :station_index, uniqueness: { scope: :route_id }
end

app/models/route.rb
class Route < ActiveRecord::Base
  validates :name, presence: true
  has_many :trains
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes, dependent: :destroy
  validate :stations_count
  before_validation :set_name
  before_validation :set_default_index

  scope :ordered_railway_stations, -> { joins(:railway_stations_routes).order('railway_stations_routes.station_index') }
  scope :with_station, ->(station) { joins(:railway_stations).where('railway_stations.id = ?', station.id) }

  def self.find_routes(start_station, end_station)
    with_station(start_station) & with_station(end_station)
  end

  def first_station
    railway_stations.first
  end

  def last_station
    railway_stations.last
  end

  private

  def set_default_index
    railway_stations_routes.each.with_index do |station, index|
      station.station_index ||= index
    end
  end

  def set_name
    self.name = "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end

  def stations_count
    errors.add(:base, 'Route must have minimum 2 station') if railway_stations_routes.count > 2
  end
end

app/models/seat_carriage.rb
class SeatCarriage < Carriage
  validates :eco_seats, presence: true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :train
  belongs_to :base_station, class_name: 'RailwayStation', foreign_key: :base_station_id
  belongs_to :end_station, class_name: 'RailwayStation', foreign_key: :end_station_id

  after_create :send_buy_notification

  after_destroy :send_cancel_notification

  def route_name
    "#{base_station.title} - #{end_station.title}"
  end

  def send_buy_notification
    TicketsMailer.buy_ticket(user, self).deliver_now
  end

  def send_cancel_notification
    TicketsMailer.cancel_ticket(user, self).deliver_now
  end
end

app/models/train.rb
class Train < ApplicationRecord
  validates :number, presence: true
  has_many :tickets
  has_many :carriages, ->(train) { order("number #{train.order_carriage ? 'ASC' : 'DESC'}") }
  belongs_to :route
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id

  def number_of_seats_by_type(carriage_type, seats_type)
    carriages.where(type: carriage_type).sum(seats_type)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :tickets
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  layout 'admin'

  protected

  def check_admin
    redirect_to root_path, notice: "You don't have access" unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    flash[:notice] = "Hi #{resource.first_name}"
    return admin_welcomes_path if current_user.admin?

    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[role_id first_name last_name email password])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @stations = RailwayStation.all
  end

  def search
    unless RailwayStation.exists?(params[:start_station]) && RailwayStation.exists?(params[:end_station])
      return redirect_to search_path
    end
    @start_station = RailwayStation.find(params[:start_station])
    @end_station = RailwayStation.find(params[:end_station])
    @routes = Route.find_routes(@start_station, @end_station)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_train, only: %i[create new]
  before_action :set_ticket, only: %i[show destroy]

  def show
  end

  def index
    @tickets = current_user.tickets
  end

  def new
    @ticket = Ticket.new
    return unless RailwayStation.exists?(params[:start_station]) && RailwayStation.exists?(params[:end_station])

    @start_station = RailwayStation.find(params[:start_station])
    @end_station = RailwayStation.find(params[:end_station])
  end

  def create
    @ticket = @train.tickets.new(ticket_params)
    @ticket.user = current_user
    return redirect_to new_train_ticket_path(@train), notice: 'Something wrong' unless @ticket.save

    return redirect_to tickets_path, notice: 'Ticket was created!' unless current_user.admin?

    redirect_to admin_tickets_path
  end

  def destroy
    redirect_to admin_tickets_path if @ticket.destroy
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def set_train
    @train = Train.find(params[:train_id])
  end

  def ticket_params
    params.require(:ticket).permit(:first_name_user, :last_name_user, :passport_user, :base_station_id, :end_station_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_errors.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(resource.errors.count, "error") %> prohibited this <%= resource.class.name %> from being saved:</h2>

    <ul>
      <% resource.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TechBaseRails - Admin</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
  <nav class="navbar navbar-light bg-light">
    <form class="container-fluid justify-content-start">
      <button class="btn btn-outline-success me-2" type="button"><%= link_to 'Trains', admin_trains_path %></button>
      <button class="btn btn-outline-success me-2" type="button"><%= link_to 'Stations', admin_railway_stations_path %></button>
      <button class="btn btn-outline-success me-2" type="button"><%= link_to 'Routes', admin_routes_path %></button>
    </form>
  </nav>

  <%= yield %>
  <footer class="fixed-bottom">
    <strong>Hrobovyi Oleksii, 2021</strong>
  </footer>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TechBaseRails</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
  <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand">Navbar</a>
      <% if user_signed_in? %>
        <button class="btn btn-outline-success d-flex"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></button>
      <% else %>
        <button class="btn btn-outline-success d-flex"><%= link_to 'Sign in', new_user_session_path %></button>
      <% end %>
    </div>
  </nav>


  <%= yield %>
  <footer class="fixed-bottom">
    <strong>Hrobovyi Oleksii, 2021</strong>
  </footer>

</div>

</body>
</html>